### ISSUE TITLE
SAR Import

### ISSUE THREAD

**Issue by NigelRel3** [NigelRel3/Architect#8]
Load SAR data, currently some errors are reported...

```
[2021-05-03 19:35:24] wh.ERROR: Slim Application Error Type: PDOException Code: 23000 Message: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'title' cannot be null File: /var/www/html/src/data/MySQL.php Line: 103 Trace: #0 /var/www/html/src/data/MySQL.php(103): PDOStatement->execute(Array) #1 /var/www/html/src/controller/UserController.php(256): Architect\data\MySQL->insert() #2 /var/www/html/src/controller/UserController.php(259): Architect\controller\UserController->saveMenu(1, 2, Array) #3 /var/www/html/src/controller/UserController.php(200): Architect\controller\UserController->saveMenu(1, NULL, Array) #4 /var/www/html/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Architect\controller\UserController->save(Object(Slim\Psr7\Request), Object(Slim\Psr7\Response), Array) #5 /var/www/html/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Psr7\Request), Object(Slim\Psr7\Response), Array) #6 
[2021-05-03 19:36:24] wh.ERROR: Slim Application Error Type: PDOException Code: 23000 Message: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'Timestamp' cannot be null File: /var/www/html/src/data/MySQL.php Line: 103 Trace: #0 /var/www/html/src/data/MySQL.php(103): PDOStatement->execute(Array) #1 /var/www/html/src/services/SARImport.php(120): Architect\data\MySQL->insert() #2 /var/www/html/src/services/SARImport.php(40): Architect\services\SARImport->importCSV('/var/www/html/s...') #3 /var/www/html/src/controller/UploadController.php(65): Architect\services\SARImport->__invoke(Object(Architect\data\architect\StatsLoad)) #4 /var/www/html/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(43): Architect\controller\UploadController->upload(Object(Slim\Psr7\Request), Object(Slim\Psr7\Response), Array) #5 /var/www/html/vendor/slim/slim/Slim/Routing/Route.php(384): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Psr7\Request), Object(Slim\Psr7\Response), Array) #6 
```

**Comment by NigelRel3** [comment]
Need to ensure that sadf is installed on the docker container!

apt update
apt install sysstat
apt clean
